### ISSUE TITLE
Changes to Authentication Procedure (probably)

### ISSUE THREAD

**Issue by Tambup** [laur89/revolut-py#2]
Referring [to change-to-web-api](github.com/laur89/revolut-py/tree/feature/change-to-web-api) branch.

I was trying to get the token through the procedure: first two steps seems working (phone number, passwd), but the third one has probably changed as inside the cli interaction it is expected to put a 6-digit code sent by email, but revolut sends me an email requiring to confirm through a link.
In general this could not be a problem, but the mail explicitly states:
> Please click the button below to log in **on the same device and browser you started to log on**.

which is never the case.
Indeed, as expected, the procedure inevitably fails.

**Comment by laur89** [comment]
If you look at the mailed URL, you'll see it contains the code (`177 551` here):
`https://app.revolut.com/login/email/confirm?token=177-551&phone=%2B33612345678`

**Comment by laur89** [comment]
Personally I'd only use `EMAIL` channel when you try to automate the auth (see #1). For interactive use `APP` & `SMS` channels are easier to use.

**Comment by Tambup** [comment]
Perfect! It works, thanks!
